
[workspace]
members = ["rg0khc", "quicpair"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
tokio = { version = "1.42.0", features = ["macros"] }
